-- Per-meter alarm limits and their dedicated alarm types.
ALTER TABLE "Device"
  ADD COLUMN "pressureUpperLimit" DOUBLE PRECISION,
  ADD COLUMN "pressureLowerLimit" DOUBLE PRECISION,
  ADD COLUMN "temperatureUpperLimit" DOUBLE PRECISION,
  ADD COLUMN "temperatureLowerLimit" DOUBLE PRECISION,
  ADD COLUMN "consumptionUpperLimit" DOUBLE PRECISION,
  ADD COLUMN "consumptionLowerLimit" DOUBLE PRECISION,
  ADD COLUMN "batteryLowerLimit" DOUBLE PRECISION;

ALTER TYPE "AlarmType" ADD VALUE IF NOT EXISTS 'PRESSURE_OUT_OF_RANGE';
ALTER TYPE "AlarmType" ADD VALUE IF NOT EXISTS 'TEMPERATURE_OUT_OF_RANGE';
ALTER TYPE "AlarmType" ADD VALUE IF NOT EXISTS 'CONSUMPTION_OUT_OF_RANGE';
ALTER TYPE "AlarmType" ADD VALUE IF NOT EXISTS 'BATTERY_LOW';
